### ISSUE TITLE
AP值为0

### ISSUE THREAD

**Issue by 1106X** [horrible-dong/TeamDETR#1]
跑DAB-DETR的时候结果正常显示  但是使用TEAM-DAB-DETR的时候 AP值一直为0

**Comment by horrible-dong** [comment]
你好，我们这边训练测试都没有问题。请提供一下你执行 Team-DAB-DETR 的命令。

**Comment by 1106X** [comment]
> 你好，我们这边训练测试都没有问题。请提供一下你执行 Team-DAB-DETR 的命令。

你好，我就是使用的readme中推荐的执行命令，其他没做改变，使用了coco2017数据集， 第一个epoch的结果全是0  我刚刚发现当epoch增加时AP值确实出现了  但是很低 增加的也很缓慢。

**Comment by horrible-dong** [comment]
再排查排查。我们刚使用 2卡，batch_size=4，跑了一个epoch，未发现异常。

![image](https://github.com/horrible-dong/TeamDETR/assets/60052756/adace15b-d8ff-4b70-89c7-b90ed60973bf)

**Comment by 1106X** [comment]
> 再排查排查。我们刚使用 2卡，batch_size=4，跑了一个epoch，未发现异常。
> 
> ![image](https://user-images.githubusercontent.com/60052756/250045239-adace15b-d8ff-4b70-89c7-b90ed60973bf.png)

好的 !   十分感谢您的回复 ！！
