### ISSUE TITLE
How to determine the scale range of the limit values for each group？

### ISSUE THREAD

**Issue by notfacezhi** [horrible-dong/TeamDETR#2]
![image](https://github.com/horrible-dong/TeamDETR/assets/62193966/65ae7007-5667-4d79-bb5a-cd221a7b14ef)
Hello, author, I would like to ask how to choose the maximum and minimum values of the defined K scale ranges mentioned in the paper in each group?

**Comment by horrible-dong** [comment]
Hi~ 
We divide the queries into three groups, each responsible for objects with relative scales in the range (0, 0.2], (0.2, 0.4] and (0.4, 1], respectively. Here is how (0, 0.2], (0.2, 0.4] and (0.4, 1] are derived:
Generally, images are scaled and padded into 640×640 when training the COCO dataset. We firstly define three absolute scale ranges (0, 128(2^7)], (128(2^7), 256(2^8)] and (256(2^8), 640], and then convert them into ones relative to the image size: (0/640, 128/640], (128/640, 256/640], (256/640, 640/640] -> (0, 0.2], (0.2, 0.4], (0.4, 1]. The value selection needs some trials, and we found the aforementioned value combination the best for training COCO.

**Comment by notfacezhi** [comment]
Thank you for your reply, I still have some questions. Regarding this paper,
1.  ![image](https://github.com/horrible-dong/TeamDETR/assets/62193966/292bdebf-89e8-4125-a902-0f71fd891b65)
when grouping queries, it should be judged logically. According to the different scales of the targets in the picture, let different groups of queries do Hungarian matching according to the obj scale, then Hungarian matching should be done within each group, right?
2. 
![image](https://github.com/horrible-dong/TeamDETR/assets/62193966/71421faa-52f6-46bc-b738-5c68213ababe)
Preference extraction part, Ai, that is, the new anchor box is directly obtained through preference extraction. In the next epoch, the new anchor box is directly used as input, and then a query is generated for training, right?

**Comment by notfacezhi** [comment]
> Hi~ We divide the queries into three groups, each responsible for objects with relative scales in the range (0, 0.2], (0.2, 0.4] and (0.4, 1], respectively. Here is how (0, 0.2], (0.2, 0.4] and (0.4, 1] are derived: Generally, images are scaled and padded into 640×640 when training the COCO dataset. We firstly define three absolute scale ranges (0, 128(2^7)], (128(2^7), 256(2^8)] and (256(2^8), 640], and then convert them into ones relative to the image size: (0/640, 128/640], (128/640, 256/640], (256/640, 640/640] -> (0, 0.2], (0.2, 0.4], (0.4, 1]. The value selection needs some trials, and we found the aforementioned value combination the best for training COCO.

Thanks for your reply.

**Comment by horrible-dong** [comment]
Your understanding of both questions is correct ~
